server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tcc_ord?useSSL=false&serverTimezone=UTC
    username: root
    password:
logging:
  level:
    org:
      mengyun:
        tcctransaction:
          recover: debug
    com :
      zoro:
        mapper : debug