server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tcc_red?useSSL=false&serverTimezone=UTC
    username: root
    password:
logging:
  level:
    org:
      mengyun:
        tcctransaction:
          recover: error
    com :
      zoro:
        mapper : debug

